project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
    - "!courseSummary.qmd"
    - "!test.qud"
    - "!ignored-dir/"
website:
  search: true
  title: "Mastering Statistics: Fundamentals of Data Analysis."
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: MathBackground.qmd
        text: Math background
      - href: probability.qmd
        text: Probability
      - href: exploratoryAnalysis.qmd
        text: Exploratory Analysis
      - text: Supervised Learning
        menu:
          - href: Inferencial.qmd
            text: Statistical Tests
          - href: linearModels.qmd
            text: Linear Models
          - href: modelAccuracy.qmd
            text: Assessing Model Accuracy
          - href: classification.qmd
            text: Classification problems
          - href: Titanic.qmd
            text: Titanic exercise
          - href: polynomialReg.qmd
            text: Polynomial Regression
          - href: survival.qmd
            text: Survival Analysis
          - href: tree.qmd
            text: Tree Based Methods
          - href: supportVectorMachines.qmd
            text: Support Vector Machines
          - text: Deep Learning with TensorFlow 
          - href: installingTensorFlow.qmd      
            text: Installing TensorFlow        
          - href: DeepLearning.qmd            
            text: Deep Learning
          - href: deepLearningTorch.qmd
            text: Deep Learning Lab with Torch
      - href: unsupervisedLearning.qmd
        text: Unsupervised Learning
      - text: Matrices
        menu:
          - href: matrix.qmd
            text: Matrix Algebra
          - href: logisticRegressionMatrixCalculation.qmd
            text: Matrices in Logistic Regression in Neural Networks
          
format: 
  html: 
    toc: true
    toc-depth: 3
    toc-title: Contents
    number-sections: true
    number-depth: 3
    embed-resources: true
    fig-align: 'center'
    fig-cap-location: margin
    fig-width: 4
    fig-height: 4
    css: custom-style.css
    page-layout: full
    crossrefs-hover: true
    footnotes-hover: true
    citations-hover: true
    code-fold: show
    code-tools: true
    code-line-numbers: true
    grid: 
      sidebar-width: 10px
      body-width: 1300px
      gutter-width: 0.5rem
    margin-left: 50px
    margin-right: 10px
    anchor-sections: true
    theme: flatly
  pdf:
    keep-tex: true
    #include-in-header: custom-style.sty
    pdf-engine: xelatex
      
prefer-html: true
encoding: "UTF-8"
execute: 
  engine: knitr
  warning: false
  echo: true
  freeze: auto
knitr:
  opts_chunk:
    label: true
    number: true
    echo: true
